### ISSUE TITLE
Add support for `IDeviceInfoProvider`

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/epi-crestron-nvx#45]
**Is your feature request related to a problem? Please describe.**
There is currently no way to get device-specific information from this plugin.

**Describe the solution you'd like**
Implement `IDeviceInfoProvider` from Essentials

**Describe alternatives you've considered**
I could individually spin up sockets to connect to each device and request data, but this seems silly and onerous.

**Additional context**
Will eventually be used for the fusion plugin to more effectively ferry data to it - this data can also be sent into the program from a completely different device bridge not related to the device being controlled.

**Comment by ngenovese11** [comment]
complete in #112
